### ISSUE TITLE
apidoc not working

### ISSUE THREAD

**Issue by gcerutti** [VirtualPlants/cellcomplex#6]

**Comment by revesansparole** [comment]
Your package and modules need to be importable for automodule to work

**Comment by gcerutti** [comment]
No idea why but the doc seems to have worked on readthedocs now, and looks kinda fine... Just check it out!

https://cellcomplex.readthedocs.io/en/latest/_dvlpt/openalea.cellcomplex.property_topomesh.html#openalea.cellcomplex.property_topomesh.property_topomesh_analysis.compute_topomesh_property

**Comment by revesansparole** [comment]
two hours of work, of course I already checked it out :)
